#!/bin/bash

# Create CloudFront Cache Invalidation
# This forces CloudFront to fetch fresh content from the origin servers

echo "🔄 CloudFront Cache Invalidation Script"
echo "========================================"
echo ""
echo "⚠️  WHY CLOUDFRONT ISN'T UPDATING:"
echo ""
echo "1. **Default Cache Behavior**: CloudFront caches static files based on:"
echo "   - Cache-Control headers from origin (if set)"
echo "   - Default TTL (Time To Live) - often 24 hours"
echo "   - Maximum TTL - can be up to 1 year"
echo ""
echo "2. **Our Static Files**: JavaScript and CSS files are cached because:"
echo "   - They don't change often (normally)"
echo "   - CloudFront assumes they're safe to cache"
echo "   - No cache-busting versioning in URLs"
echo ""
echo "3. **Edge Locations**: CloudFront has 400+ edge locations worldwide"
echo "   - Each location caches independently"
echo "   - Your browser connects to nearest edge"
echo "   - That edge may have old cached version"
echo ""
echo "📝 TO CREATE AN INVALIDATION (requires AWS Console access):"
echo ""
echo "1. Go to AWS Console → CloudFront"
echo "2. Find distribution: d225ar6c86586s.cloudfront.net"
echo "3. Click on the distribution ID"
echo "4. Go to 'Invalidations' tab"
echo "5. Click 'Create Invalidation'"
echo "6. Enter these paths:"
echo "   /static/js/*"
echo "   /static/css/*"
echo "   /static/js/modules/chat/core/*"
echo "7. Click 'Create Invalidation'"
echo ""
echo "⏱️ Invalidation takes 5-10 minutes to propagate to all edge locations"
echo ""
echo "🔧 IMMEDIATE WORKAROUNDS:"
echo ""
echo "1. **Use Direct ALB URL** (bypasses CloudFront completely):"
echo "   http://chatmrpt-staging-alb-752380251.us-east-2.elb.amazonaws.com"
echo ""
echo "2. **Add version parameter** to force cache miss:"
echo "   https://d225ar6c86586s.cloudfront.net?v=$(date +%s)"
echo ""
echo "3. **Browser DevTools Method**:"
echo "   - Open DevTools (F12)"
echo "   - Network tab → Disable cache"
echo "   - Keep DevTools open while refreshing"
echo ""
echo "4. **Check Response Headers** to see cache status:"
echo "   - x-cache: Hit from cloudfront = OLD cached version"
echo "   - x-cache: Miss from cloudfront = NEW fresh version"
echo ""
echo "🎯 ROOT CAUSE:"
echo "CloudFront is designed for performance, so it aggressively caches"
echo "static assets. When we deployed the frontend changes, CloudFront's"
echo "edge servers didn't know the files changed, so they keep serving"
echo "the old cached versions until:"
echo "  - Cache expires (based on TTL)"
echo "  - Manual invalidation is created"
echo "  - Cache is bypassed (direct ALB access)"
echo ""

# Try to get distribution ID programmatically
echo "📊 Attempting to get CloudFront distribution details..."
echo ""

# Check if we can SSH to instance and get CloudFront info from there
KEY_PATH="/tmp/chatmrpt-key2.pem"
if [ -f "$KEY_PATH" ]; then
    echo "Checking server headers to understand caching..."
    ssh -i "$KEY_PATH" -o StrictHostKeyChecking=no ec2-user@3.21.167.170 \
        "curl -I http://localhost/static/js/modules/chat/core/message-handler.js 2>/dev/null | grep -E '(Cache-Control|ETag|Last-Modified)'" || true
fi

echo ""
echo "💡 PERMANENT FIX for future deployments:"
echo "   - Implement cache-busting with version numbers in URLs"
echo "   - Set shorter TTL for development/staging"
echo "   - Use CloudFront API to auto-invalidate on deployment"
echo ""