#!/bin/bash
# Script to check AWS logs for dashboard generation issues

echo "=== Instructions to check AWS logs for dashboard issues ==="
echo ""
echo "1. SSH into the AWS server:"
echo "   ssh -i aws_files/chatmrpt-key.pem ubuntu@3.137.158.17"
echo ""
echo "2. Check application logs:"
echo "   sudo journalctl -u chatmrpt -n 100 | grep -i 'dashboard\|export'"
echo ""
echo "3. Check for recent export attempts:"
echo "   sudo journalctl -u chatmrpt --since '1 hour ago' | grep -i 'itn.*export\|dashboard'"
echo ""
echo "4. Check if dashboard files are being created:"
echo "   find /home/ubuntu/chatmrpt/instance/exports -name '*dashboard*.html' -mtime -1"
echo ""
echo "5. Check for errors during dashboard generation:"
echo "   sudo journalctl -u chatmrpt -n 200 | grep -i 'error.*dashboard\|failed.*dashboard'"
echo ""
echo "6. Check the export directory contents:"
echo "   ls -la /home/ubuntu/chatmrpt/instance/exports/*/itn_export_*/"
echo ""
echo "7. Check if ZIP files contain dashboard:"
echo "   for zip in /home/ubuntu/chatmrpt/instance/exports/*/*.zip; do echo \"=== \$zip ===\"; unzip -l \"\$zip\" | grep -i dashboard; done"